---
title: "Community Service & Activities"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Reviewing Service

* **Journal Reviewer**: Nature Communications, Interface Focus, Biomicrofluidics, Scientific Reports

* **Conference Reviewer**: Summer Biomechanics, Bioengineering, and Biotransport Conference, Biomedical Engineering Society Annual Meeting

## Conference Organizer

1. Session Co-chair, Emerging Topics: Extracellular Matrix Adaption, Alterations, and Therapy in Soft Tissue Mechanics session at the Summer Biomechanics, Bioengineering, and Biotransport Conference, Lake Geneva, WI, June 11-14, 2024.
2. Facilitator, “Engineering Life, Designing Our Futures: A Conversation about New Biological System”, A public event by Museum of Science of Boston, 2022.
3. Conference Assistant, Keystone Symposia: Engineering Multi-Cellular Living System, Keystone, CO, April 03-06, 2022.
4. Student Paper Competition Judge, Summer Biomechanics, Bioengineering, and Biotransport Conference, 2019-2024.
5. Co-organizer, Columbia University Biomechanics Seminar Series, 2019-2021.
6. Organizing Volunteer, 16th International Symposium on Computer Methods in Biomechanics and Biomedical Engineering and the 4th Conference on Imaging and Visualization, New York, NY, August 14-16, 2019.
7. Assistant Organizer, 8th Northeast Complex Fluids & Soft Matter Workshop, New York, NY, January 12, 2018.

## Professional Affiliations

* American Society of Mechanical Engineers (ASME)
* Biomedical Engineering Society (BMES)
* American Society for Cell Biology (ASCB)
* New York Academy of Sciences (NYAS)

## Outreach & Community Engagement

* Vice President, MIT Chinese Entrepreneur Organization, 2022-2024
* Co-organizer, MIT Postdoc Buddy Program, 2022-2023
* Networking Chair, Student Leadership Committee, ASME-BED, 2019-2021
* Chair, Columbia University Interschool Governing Board, 2019-2020
* President, Columbia University Chinese Students and Scholars Association, 2018-2019
* Secretary, Columbia Mechanical Engineering Graduate Association, 2016-2017

