---
title: "NYC Restaurant Inspections"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```

```{r}
data("rest_inspec")

rest_inspec = 
  rest_inspec %>%
  select(boro, building, critical_flag, cuisine_description, score, zipcode, grade) %>% 
  filter(grade %in% c("A", "B", "C"), boro != "Missing") %>%
  mutate(
    boro = str_to_title(boro),
    cuisine_description = replace(cuisine_description, cuisine_description == "Latin (Cuban, Dominican, Puerto Rican, South & Central American)", "Latin"))

common_cuisine = 
  rest_inspec %>% 
  count(cuisine_description, sort = TRUE) %>% 
  top_n(10) %>% 
  select(cuisine_description) %>% 
  inner_join(rest_inspec, ., by = "cuisine_description")
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Restaurant Inspection Results Distribution in NYC

```{r}
set.seed(1)

plot_1 = 
  common_cuisine %>%
  sample_n(10000) %>%
  mutate(borough = fct_infreq(boro)) %>%
  group_by(borough) %>% 
  plot_ly(x = ~borough, y = ~score, type = "scatter", mode = "markers", color = ~grade, alpha = .5)

plot_2 = 
  common_cuisine %>%
  sample_n(10000) %>%
  mutate(borough = fct_infreq(boro)) %>%
  group_by(borough) %>% 
  summarise(score = mean(score)) %>% 
  plot_ly(x = ~borough, y = ~score, name = "mean score", type = "scatter", mode = "lines")

subplot(plot_1, plot_2, nrows = 2, shareX = TRUE, shareY = TRUE) %>% 
  layout(title = "NYC Restaurant Inspection Results")

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Top 10 Restaurant Cuisine Type Inspection Score Distribution in Manhattan (the lower, the better)

```{r}
common_cuisine %>% 
  filter(boro == "Manhattan") %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>%
  plot_ly(x = ~cuisine_description, y = ~score, color = ~cuisine_description, type = "box",
          colors = "Set2")
```

### Chart C: Top 10 Restaurant Cuisine Type Distribution in NYC

```{r}
common_cuisine %>%
  mutate(
    borough = fct_infreq(boro),
    cuisine_description = fct_infreq(cuisine_description)) %>% 
  group_by(borough, cuisine_description) %>% 
  summarise(n = n()) %>%
  plot_ly(x = ~borough, y = ~n, color = ~cuisine_description, type = "bar") %>% 
  layout(yaxis = list(title = 'restaurant number'), barmode = 'stack')

```

